### 增加用户
POST http://localhost:8085/api/v1/user/addUser
Content-Type: application/json

{
  "username": "123",
  "password": "123123"
}

### 删除用户
DELETE http://localhost:8085/api/v1/user/deleteById?id=1

### 更新用户描述
POST http://localhost:8085/api/v1/user/updateDescribeById
Content-Type: application/x-www-form-urlencoded

id=0047f326-a461-4571-9cbd-76d6c92f047c&description=123456

### 更新用户密码
POST http://localhost:8085/api/v1/user/updatePasswordById
Content-Type: application/x-www-form-urlencoded

id=0047f326-a461-4571-9cbd-76d6c92f047c&password=111111

### id查找
GET http://localhost:8085/api/v1/user/findById?id=0047f326-a461-4571-9cbd-76d6c92f047c

### 姓名查找
GET http://localhost:8085/api/v1/user/findByUsername?username=test11

### 获取全部
GET http://localhost:8085/api/v1/user/findAll
